### PR TITLE
Update bot.po

### PR DESCRIPTION
**Pull request by Davi-the-Mudkip**

### CODE REVIEW

**Comment by Theelx** [comment]
can you change the msgid for xproles for the other languages too

**Comment by Davi-the-Mudkip** [comment]
> can you change the msgid for xproles for the other languages too

Can you do it yourself? There are many lines to change.

**Comment by Theelx** [comment]
i cannot do it myself, i don't have much free time because of school

**Comment by Davi-the-Mudkip** [comment]
> i cannot do it myself, i don't have much free time because of school

Alright, so I'll try to do it myself.

**Comment by Davi-the-Mudkip** [comment]
> can you change the msgid for xproles for the other languages too

Done

**Pull request merged**
